definition  : function
            | definition function

function    : <identifier> ( ide ) = expression ;

expression  : add;

add : mul
    | add + mul
    | add - mul
    ;

mul : cons
    | mul * cons
    | mul / cons
    ;

cons: call
    | ( expression )

call: NUM
    | <ide> ( NUM ) 

NUM : <number>;
